#!/bin/bash

if [ `whoami` != "git" ]; then
	echo "Only user git can prepare."
	exit 1
fi

if [ $# -eq 0 ]; then
	echo "Usage: prepare [name]"
	exit 1
fi

NAME=$1
DEST=/tmp/$NAME

cleanExit () {
	dirs -c > /dev/null
	if [ -f "$DEST" ]; then
		rm -Rf $DEST
	fi
	exit $1
}

mkdir -p $DEST
git --work-tree=$DEST checkout -f

pushd $DEST > /dev/null
if [ -f "package.json" ]; then
	if npm install; then
		echo "npm install success."
	else
		echo "npm install failed."
		cleanExit 1
	fi
fi
if [ -f "bower.json" ]; then
	if bower install; then
		echo "bower install success."
	else
		echo "bower install failed."
		cleanExit 1
	fi
fi
if grep -q \"test\" package.json; then 
	if npm test; then
		echo "npm test success."
	else
		echo "npm test failed."
		cleanExit 1
	fi
else
	echo "No test script."
fi
if grep -q \"postdeploy\" package.json; then
	if npm run postdeploy; then
		echo "postdeploy success."
	else
		echo "postdeploy failed."
		cleanExit 1
	fi
else
	echo "No postdeploy script."
fi
popd > /dev/null
